version: '3.8'

networks:
  nexus:
    driver: bridge

services:
  nexus:
    restart: always
    container_name: nexus
    image: sonatype/nexus3
    volumes:
      - data/nexus/data:/sonatype-work:z
    ports:
      - "8081:8081"
    environment:
      - NEXUS_CONTEXT_PATH=/nexus
      - NEXUS_PROXY_PORT=80
    networks:
      - nexus
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8081/"]
      interval: 30s
      timeout: 10s
      retries: 3
